# Using an official jdk17 image
FROM openjdk:17-jdk-slim
# Set working directory


# Set working directory
WORKDIR /app

# Install maven and build the project

RUN apt-get update && apt-get install -y maven && mvn clean package -DskipTests


# Expose the application's port
EXPOSE 8080

# Run the java application
CMD service mysql start && java -jar target/ecommerce-0.0.1-SNAPSHOT.jar
