# Using an official jdk17 image
FROM openjdk:17-jdk-slim
FROM mysql:5.7
# Set working directory


ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mysql
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

# Install mysql client and server
RUN apt-get update && apt-get install -y mysql-server

# Set working directory
WORKDIR /app

# Copy the checked out source code into the container
COPY ./backend .
COPY ./backend/src/main/resources/application.properties /app/src/main/resources/application.properties

# Install maven and build the project

RUN apt-get update && apt-get install -y maven && mvn clean package -DskipTests


# Expose the application's port
EXPOSE 8080 3306

# Run the java application
CMD service mysql start && java -jar target/ecommerce-0.0.1-SNAPSHOT.jar