version: '3'
services:
  backend:
     build:
      context: .
      dockerfile: Dockerfile-backend
     image: sreemare/ecomm-app:latest
     ports:
      - "8080:8080"
     depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
