name: Build and Push to AWS ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout repository
      uses : actions/checkout@v4  #checkout the repo
# Setting up docker
    - name: Check docker version
      run: docker --version #verify docker installation
    - name: Setup docker buildx (this is needed for docker build and pushing images)
      run: docker/setup-buildx-action@v2
# Login to Docker Hub
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        username: sreemare
        password: dckr_pat_LCcXpEsoXaija9CUaxSYO0ZLWxU

    - name: current directory
      run: pwd
# Build docker image
    - name: create docker image for backend
      run : docker build --no-cache -f Dockerfile-backend -t ecomm-app:latest .

# Push docker image to docker hub
    - name: push docker image to docker hub
      run: |
          docker push sreemare/ecomm-app:latest
